# Generated by Django 2.2.3 on 2019-12-25 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manaplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='manaplatform.Group'),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='manaplatform.User'),
        ),
    ]
