# Generated by Django 2.2.3 on 2019-12-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manaplatform', '0003_auto_20191225_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appid',
        ),
    ]
